version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - 7445:5432
    volumes:
      - ~/.docker-conf/postgres/data/:/var/lib/postgresql/data
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
