spring:
  application:
    name: RabbitMqCourse
  datasource:
    url: jdbc:postgresql://localhost:7445/mydatabase
    username: postgres
    password: example
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
